[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
agm_core = { path = "../agm-core" }
clap = { version = "4.4.11", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
url = "2.5.0"
serde_yaml = "0.9.34"
walkdir = "2.5.0"
zip = "0.6.0"